Repository AllenInstitute/MIES, pull requests merged in 2020-11, with the labels that each got.

#725 RemoveUnusedRows: Handle non-existing NOTE_INDEX gracefully
  Packages/Conversion/MIES_MassExperimentProcessing.ipf
  Packages/MIES/MIES_Utilities.ipf
  Packages/Testing-MIES/UTF_Utils.ipf
Labels: Patch Seq

#731 Fix sweep rollback deleting the wrong sweeps
  Packages/MIES/MIES_Constants.ipf
  Packages/MIES/MIES_DAEphys.ipf
  Packages/MIES/MIES_MiesUtilities.ipf
  Packages/MIES/MIES_SweepSaving.ipf
  Packages/Testing-MIES/UTF_BasicHardwareTests.ipf
  Packages/Testing-MIES/UTF_HardwareMain.ipf
  Packages/Testing-MIES/UTF_Utils.ipf
  Packages/Testing-MIES/UserAnalysisFunctions.ipf
Labels: PR:NeedsBackport, Patch Seq

#724 NWB_ExportAllData: Handle missing config waves
  Packages/MIES/MIES_MiesUtilities.ipf
  Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
Labels: PR:NeedsForwardPort, Patch Seq

#753 PA: Speed optimization in PA_LayoutGraphs
  Packages/MIES/MIES_PulseAveraging.ipf
Labels: Optimization, PA plot
