Repository AllenInstitute/MIES, pull requests merged in 2023-08, with the labels that each got.

#1822 Add TTL support to SF
  Packages/MIES/MIES_BrowserSettingsPanel.ipf
  Packages/MIES/MIES_Constants.ipf
  Packages/MIES/MIES_DataBrowser.ipf
  Packages/MIES/MIES_DataBrowser_Macro.ipf
  Packages/MIES/MIES_Epochs.ipf
  Packages/MIES/MIES_MiesUtilities.ipf
  Packages/MIES/MIES_NeuroDataWithoutBorders.ipf
  Packages/MIES/MIES_SweepFormula.ipf
  Packages/MIES/MIES_SweepFormula_Helpers.ipf
  Packages/doc/SweepFormula.rst
  Packages/tests/Basic/UTF_EpochswoHardware.ipf
  Packages/tests/Basic/UTF_SweepFormula.ipf
  Packages/tests/UTF_HelperFunctions.ipf
Labels: DataBrowser, SweepFormula

#1804 CONF: Clear HS association on DAEphys window restore for HS w/o amp
  Packages/MIES/MIES_Configuration.ipf
  Packages/MIES/MIES_Constants.ipf
  Packages/MIES/MIES_DAEphys.ipf
  Packages/MIES/MIES_DAEphys_Macro.ipf
  Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf
  Packages/tests/HardwareBasic/UTF_ConfigurationHardware.ipf
  Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf
  Packages/tests/UTF_Constants.ipf
  Packages/tests/UTF_HelperFunctions.ipf
Labels: JSON Configuration

#1850 CI: Disable report generation for release branches [ForwardPort on main]
  .github/workflows/build-release.yml
Labels: ContinousIntegration

#1849 CI: Disable report generation for release branches
  .github/workflows/build-release.yml
Labels: ContinousIntegration

#1862 GetAllFilesRecursivelyFromPath: Fix returning empty results at the end
  .gitignore
  Packages/MIES/MIES_Utilities.ipf
  Packages/tests/Basic/UTF_Utils.ipf
Labels: PR:NeedsForwardPort
